---
server:
  port: 51101
spring:
  data:
    mongodb:
      host: 10.1.140.19
      port: 27017
driver:
  event:
    producer:
      topic: ${driver.message.broker.type}://${driver.message.broker.hostname}:${driver.message.broker.port}/${driver.message.broker.producer.exchange.name}${driver.message.broker.producer.options}
  message:
    broker: 
      port: 5672
      hostname: 10.1.140.19
      type: rabbitmq
      producer: 
        options: ?exchangeType=fanout&durable=true&username=${rabbitmq.username}&password=${rabbitmq.password}
        exchange:
          name: driverEvents
rabbitmq:
  username: guest
  password: guest
